services:
    web:
        image: nginx
        volumes:
            - ./.docker/conf/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - .:/var/www/
            - ./.docker/log/nginx:/var/log/nginx/
            - ./.docker/sert/:/etc/nginx/ssl/
        ports:
            - 80:80
        restart: always
        depends_on:
            - php
            - mysql
        networks:
            default:
                ipv4_address: 10.5.0.5
    php:
        build: .docker
        restart: always
        volumes:
            - ./.docker/conf/php/php.ini:/usr/local/etc/php/conf.d/php.ini
            - .:/var/www/
        #            - ./.docker/log/symfony:/var/www/var/log:cached
        extra_hosts:
            - "host.docker.internal:host-gateway"
        networks:
            default:
                ipv4_address: 10.5.0.6
    mysql:
        image: mariadb:10.6
        ports:
            - '3307:3306'
        volumes:
            - ./.docker/conf/mysql/db-data:/var/lib/mysql
            - ./.docker/conf/mysql/config:/etc/mysql/conf.d
            - ./.docker/log/mysql/:/var/lib/mysql/logs
            - ./.docker/conf/mysql/init:/docker-entrypoint-initdb.d
            - .:/var/www/
        environment:
            MYSQL_DATABASE: 'admin_core'
            MYSQL_ROOT_PASSWORD: 'password'
        restart: always
        networks:
            default:
                ipv4_address: 10.5.0.9

    phpmyadmin:
        image: phpmyadmin
        restart: always
        ports:
            - 8282:80
        environment:
            PMA_HOST: mysql
        networks:
            default:
                ipv4_address: 10.5.0.10

    redis:
        image: redis:alpine
        restart: always
        ports:
            - "6379:6379"
        volumes:
            - ./.docker/conf/redis/redis.conf:/usr/local/etc/redis/redis.conf
            - ./.docker/conf/redis/data/:/data/
        networks:
            default:
                ipv4_address: 10.5.0.1

networks:
    default:
        ipam:
            config:
                - subnet: 10.0.0.0/10
